In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("./all_questions_answers_scores.csv")
df.columns

Index(['Unnamed: 0', 'model', 'category_id', 'iteration_number',
       'question_index', 'question', 'model_answer', 'gold_answer', 'MedGPT1',
       'MedGPT2', 'MedGPT3', 'MedGPT4', 'MedGPT5', 'MedGPT_overall_score',
       'precision', 'recall', 'f1_score', 'synonyms_precision_dict',
       'synonyms_recall_dict', 'synonyms_f1_dict', 'synonyms_precision_snomed',
       'synonyms_recall_snomed', 'synonyms_f1_snomed', 'synonyms_precision_wn',
       'synonyms_recall_wn', 'synonyms_f1_wn',
       'synonyms_lemmatized_precision_dict', 'synonyms_lemmatized_recall_dict',
       'synonyms_lemmatized_f1_dict',
       'synonyms_lemmatized_precision_dict_bipartite',
       'synonyms_lemmatized_recall_dict_bipartite',
       'synonyms_lemmatized_f1_dict_bipartite',
       'synonyms_lemmatized_precision_dict_one2many',
       'synonyms_lemmatized_recall_dict_one2many',
       'synonyms_lemmatized_f1_dict_one2many',
       'synonyms_lemmatized_precision_snomed',
       'synonyms_lemmatized_recall_snomed', 'synonyms_lemmatized_f1_snomed',
       'synonyms_lemmatized_precision_wn', 'synonyms_lemmatized_recall_wn',
       'synonyms_lemmatized_f1_wn'],
      dtype='object')

In [17]:
df

,Unnamed: 0,model,category_id,iteration_number,question_index,question,model_answer,gold_answer,MedGPT1,MedGPT2,...,synonyms_lemmatized_f1_dict_bipartite,synonyms_lemmatized_precision_dict_one2many,synonyms_lemmatized_recall_dict_one2many,synonyms_lemmatized_f1_dict_one2many,synonyms_lemmatized_precision_snomed,synonyms_lemmatized_recall_snomed,synonyms_lemmatized_f1_snomed,synonyms_lemmatized_precision_wn,synonyms_lemmatized_recall_wn,synonyms_lemmatized_f1_wn
0,0,Llama 3.3-70B-Instruct,1,1,0,How is HIV diagnosed?,HIV diagnosis typically involves a combination...,HIV is diagnosed through HIV testing. There ar...,3.0,3.0,...,0.024096,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578,0.142857,0.205882,0.168675
1,1,Llama 3.3-70B-Instruct,1,1,1,What are the different stages of HIV?,The different stages of HIV are:\n\n1. **Acute...,The different stages of HIV are either defined...,4.0,3.0,...,0.042553,0.189189,0.700000,0.297872,0.162162,0.600000,0.255319,0.135135,0.500000,0.212766
2,2,Llama 3.3-70B-Instruct,1,1,2,How is HIV transmitted?,HIV (Human Immunodeficiency Virus) is primaril...,HIV is spread from the body fluids of an infec...,4.0,4.0,...,0.097561,0.233333,0.636364,0.341463,0.133333,0.363636,0.195122,0.166667,0.454545,0.243902
3,3,Llama 3.3-70B-Instruct,1,1,3,What comorbidities are common among people liv...,People living with HIV often experience variou...,The most common comorbidities amongst patients...,3.0,3.0,...,0.000000,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593
4,4,Llama 3.3-70B-Instruct,1,1,4,How can HIV be prevented?,HIV prevention methods include:\n\n1. **Using ...,HIV prevention involves several key strategies...,4.0,4.0,...,0.083333,0.468750,0.375000,0.416667,0.437500,0.350000,0.388889,0.437500,0.350000,0.388889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913,5413,Llama 3.1-8B-Instruct RAG,5,5,19,A 32-year-old man with a past medical history ...,Based on the provided clinical presentation an...,The etiology of these lesions is HPV (types 6 ...,4.0,4.0,...,0.000000,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857
4914,5414,Llama 3.1-8B-Instruct RAG,5,5,20,"A 24-year-old man, who recently migrated from ...","Based on the provided clinical scenario, the p...",Continue antitubercular therapy and antiretrov...,3.0,2.0,...,0.000000,0.037037,0.500000,0.068966,0.018519,0.250000,0.034483,0.037037,0.500000,0.068966
4915,5415,Llama 3.1-8B-Instruct RAG,5,5,21,A 37-year-old African-American man presents to...,"Based on the provided clinical scenario, I wou...",Focal segmental glomerulosclerosis (FSGS) asso...,4.0,4.0,...,0.000000,0.090909,0.571429,0.156863,0.068182,0.428571,0.117647,0.068182,0.428571,0.117647
4916,5416,Llama 3.1-8B-Instruct RAG,5,5,22,A 39-year-old man comes to the emergency depar...,Based on the provided clinical scenario and th...,A Treponemal test is most likely to confirm th...,1.0,1.0,...,0.000000,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455
4917,5417,Llama 3.1-8B-Instruct RAG,5,5,23,A 51-year-old woman with AIDS presents to her ...,The patient's presentation with decreased urin...,Tumor lysis syndrome is the most likely diagno...,4.0,3.0,...,0.000000,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897

In [11]:
df["category_id"].value_counts()

category_id
3    1438
5    1200
2     720
1     660
4     660
Name: count, dtype: int64

In [12]:
df["question_index"].value_counts()

question_index
0     290
6     290
1     290
10    290
9     290
7     290
8     290
5     290
4     290
3     290
2     290
11    170
18    110
22    110
21    110
20    110
19    110
23    110
17    110
16    110
15    110
14    110
13    110
12    108
Name: count, dtype: int64

In [13]:
df["model"].value_counts()

model
Llama 3.3-70B-Instruct       410
Meditron 3-70B               410
NVLM-70B                     410
Claude 3.5 Sonnet            410
Llama 3.1-8B-Instruct        410
Llama 3.2-1B-Instruct        410
Gemini 2.5 Pro               410
Gemma 3 27B                  410
MedGemma 27B                 410
Med42-70B                    408
MedGemma 27B RAG             290
Llama 3.1-8B-Instruct RAG    290
Name: count, dtype: int64

In [14]:
df["iteration_number"].value_counts()

iteration_number
1    936
4    936
5    936
2    935
3    935
Name: count, dtype: int64

In [30]:
import os
import re
import json
import glob
import pandas as pd

# ----------------------------
# 1) Load CSV
# ----------------------------
df = pd.read_csv("all_questions_answers_scores.csv")

# Insert "reasoning" right after MedGPT5
insert_at = df.columns.get_loc("MedGPT5") + 1
if "reasoning" not in df.columns:
    df.insert(insert_at, "reasoning", pd.NA)

# ----------------------------
# 2) Paths / constants
# ----------------------------
models_root = "/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score"  # your notebook working dir: model_answers/results-GPT-score/

GOLD_MODEL_NAME = "Rephrased Gold Answers"
GOLD_BASE_DIR = (
    "/cluster/home/gcardenal/HIV/medical_llm_evaluation/"
    "deploy_medical_llm_evaluation/gold_standard_rephrasing/"
    "results-GPT-score-rephrased"
)

# ----------------------------
# 3) Helpers
# ----------------------------
FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL | re.IGNORECASE)
NAME_RE = re.compile(r"answers_category_(\d+)\.(\d+)_", re.IGNORECASE)

def extract_json_from_response(text: str):
    if not isinstance(text, str):
        return None
    m = FENCE_RE.search(text)
    if not m:
        return None
    try:
        return json.loads(m.group(1).strip())
    except json.JSONDecodeError:
        return None

def extract_reason(text: str):
    obj = extract_json_from_response(text)
    if isinstance(obj, dict) and isinstance(obj.get("reason"), str):
        return obj["reason"].strip()
    return None

def parse_category_iteration_from_filename(path: str):
    base = os.path.basename(path)
    m = NAME_RE.search(base)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))

def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())

# ----------------------------
# 4) Map folders -> df.model names
# ----------------------------
folder_to_model = {
    "Claude": "Claude 3.5 Sonnet",
    "Gemini_2.5Pro": "Gemini 2.5 Pro",
    "Llama_cluster": "Llama 3.3-70B-Instruct",
    "Llama-1B": "Llama 3.2-1B-Instruct",
    "Llama-8B": "Llama 3.1-8B-Instruct",
    "Gemma-3-27B": "Gemma 3 27B",
    "MedGemma-3-27B": "MedGemma 27B",
    "Med42": "Med42-70B",
    "Meditron_cluster": "Meditron 3-70B",
    "NVLM": "NVLM-70B",
    "MedGemma-3-27B-RAG": "MedGemma 27B RAG",
    "Llama-8B-RAG": "Llama 3.1-8B-Instruct RAG",
}

# ----------------------------
# 5) Build mapping:
#    (model, category_id, iteration_number) -> list_of_reasons_in_order
#    + diagnostics: (model, cat, iter, json_path) -> list of entry indices where reason is None
# ----------------------------
reasons_by_group = {}
none_reason_entries = {}  # key: (model, category, iter, path) -> [entry_idx, ...]

def add_file_reasons(model_name: str, json_path: str):
    ci = parse_category_iteration_from_filename(json_path)
    if ci is None:
        return
    category_id, iteration_number = ci

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return

    if not isinstance(data, list):
        return

    reasons = []
    none_idxs = []

    for idx, item in enumerate(data):
        if not isinstance(item, dict):
            reasons.append(None)
            none_idxs.append(idx)
            continue

        r = extract_reason(item.get("response"))
        reasons.append(r)  # keep position even if None (preserves alignment)

        if r is None:
            none_idxs.append(idx)

    reasons_by_group[(model_name, category_id, iteration_number)] = reasons

    if none_idxs:
        none_reason_entries[(model_name, category_id, iteration_number, json_path)] = none_idxs

# --- regular model folders ---
for folder, model_name in folder_to_model.items():
    folder_path = os.path.join(models_root, folder)
    json_paths = glob.glob(os.path.join(folder_path, "**", "GPT-score_*.json"), recursive=True)
    for jp in json_paths:
        add_file_reasons(model_name, jp)

# --- gold rephrased folder ---
gold_paths = glob.glob(
    os.path.join(GOLD_BASE_DIR, "GPT-score_rephrased_true_answers_answers_category_*.json")
)
for jp in gold_paths:
    add_file_reasons(GOLD_MODEL_NAME, jp)

print(f"Loaded reason lists for groups: {len(reasons_by_group):,}")

# ----------------------------
# 6) Fill df['reasoning'] by group order (sorted by question_index)
#    + track which df rows were expected to have reasoning (group exists)
# ----------------------------
df["reasoning"] = pd.NA  # reset in case rerun

expected_reasoning_rows = set()
filled = 0

for (model_name, category_id, iteration_number), idxs in df.groupby(
    ["model", "category_id", "iteration_number"]
).groups.items():

    reasons = reasons_by_group.get((model_name, int(category_id), int(iteration_number)))
    if not reasons:
        continue

    # these rows correspond to a group that exists in JSON => "expected"
    expected_reasoning_rows.update(idxs)

    # assign by CSV question order
    group_index_list = list(idxs)
    group_sorted = sorted(group_index_list, key=lambda i: df.at[i, "question_index"])

    n = min(len(group_sorted), len(reasons))
    for k in range(n):
        r = reasons[k]
        if r:  # only fill if we successfully extracted a reason
            df.at[group_sorted[k], "reasoning"] = r
            filled += 1

print("Reasoning filled cells:", filled)

# ----------------------------
# 6b) Diagnostics
# ----------------------------

# A) Rows that belong to a group with JSONs but still have null reasoning
null_expected_mask = df.index.isin(expected_reasoning_rows) & df["reasoning"].isna()
null_expected_df = df.loc[
    null_expected_mask,
    ["model", "category_id", "iteration_number", "question_index"]
].sort_values(["model", "category_id", "iteration_number", "question_index"])

print("\nNull reasoning rows (group matched but no reason extracted):")
print(f"{len(null_expected_df)} rows")
print(null_expected_df.head(50))

# B) Rows with NO matching JSON group at all
all_group_keys = set(reasons_by_group.keys())
df_group_keys = set(
    (row.model, int(row.category_id), int(row.iteration_number))
    for row in df.itertuples()
)
unmatched_groups = df_group_keys - all_group_keys

unmatched_mask = df.apply(
    lambda r: (r.model, int(r.category_id), int(r.iteration_number)) in unmatched_groups,
    axis=1,
)
unmatched_df = df.loc[
    unmatched_mask,
    ["model", "category_id", "iteration_number", "question_index"]
].sort_values(["model", "category_id", "iteration_number", "question_index"])

print("\nRows with NO matching JSON group at all:")
print(f"{len(unmatched_df)} rows")
print(unmatched_df.head(50))

# C) Which JSON entries had None reasons (per file)
print("\nJSON entries with None reason (by file):")
if not none_reason_entries:
    print("None")
else:
    # show a compact summary
    total_none = sum(len(v) for v in none_reason_entries.values())
    print(f"Files with >=1 None reason: {len(none_reason_entries)}")
    print(f"Total None entries across those files: {total_none}")

    # print first N files (adjust as needed)
    N = 20
    shown = 0
    for (model_name, cat, it, path), idx_list in sorted(
        none_reason_entries.items(),
        key=lambda kv: (kv[0][0], kv[0][1], kv[0][2], kv[0][3]),
    ):
        print(f"- {model_name} | cat={cat} iter={it} | none_count={len(idx_list)} | file={path}")
        print(f"  entry_indices (0-based): {idx_list[:50]}" + (" ..." if len(idx_list) > 50 else ""))
        shown += 1
        if shown >= N:
            remaining = len(none_reason_entries) - N
            if remaining > 0:
                print(f"... ({remaining} more files not shown)")
            break

# ----------------------------
# 7) Save output
# ----------------------------
out_path = "all_questions_answers_scores_plus_reason.csv"
df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

# quick sanity:
print("Non-null reasoning:", df["reasoning"].notna().sum(), "/", len(df))
print(
    df.loc[
        df["reasoning"].notna(),
        ["model", "category_id", "iteration_number", "question_index", "reasoning"],
    ].head(3)
)

Loaded reason lists for groups: 380
Reasoning filled cells: 4899

Null reasoning rows (group matched but no reason extracted):
19 rows
          model  category_id  iteration_number  question_index
1287  Med42-70B            2                 1               2
1290  Med42-70B            2                 1               5
1299  Med42-70B            2                 2               2
1302  Med42-70B            2                 2               5
1311  Med42-70B            2                 3               2
1323  Med42-70B            2                 4               2
1326  Med42-70B            2                 4               5
1335  Med42-70B            2                 5               2
1338  Med42-70B            2                 5               5
1357  Med42-70B            3                 1              12
1363  Med42-70B            3                 1              18
1367  Med42-70B            3                 1              22
1387  Med42-70B            3                 2              19
1410  Med42-70B            3                 3              19
1427  Med42-70B            3                 4              12
1433  Med42-70B            3                 4              18
1451  Med42-70B            3                 5              12
1457  Med42-70B            3                 5              18
1479  Med42-70B            4                 2               5

Rows with NO matching JSON group at all:
0 rows
Empty DataFrame
Columns: [model, category_id, iteration_number, question_index]
Index: []

JSON entries with None reason (by file):
Files with >=1 None reason: 11
Total None entries across those files: 19
- Med42-70B | cat=2 iter=1 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.1_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=2 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.2_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=3 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.3_HIV_EQ.json
  entry_indices (0-based): [2]
- Med42-70B | cat=2 iter=4 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.4_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=5 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.5_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=3 iter=1 | none_count=3 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.1_HIV_EQ.json
  entry_indices (0-based): [12, 18, 22]
- Med42-70B | cat=3 iter=2 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.2_HIV_EQ.json
  entry_indices (0-based): [18]
- Med42-70B | cat=3 iter=3 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.3_HIV_EQ.json
  entry_indices (0-based): [18]
- Med42-70B | cat=3 iter=4 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.4_HIV_EQ.json
  entry_indices (0-based): [12, 18]
- Med42-70B | cat=3 iter=5 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.5_HIV_EQ.json
  entry_indices (0-based): [12, 18]
- Med42-70B | cat=4 iter=2 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_4.2_HIV_EQ.json
  entry_indices (0-based): [5]

Saved: all_questions_answers_scores_plus_reason.csv
Non-null reasoning: 4899 / 4918
                    model  category_id  iteration_number  question_index  \
0  Llama 3.3-70B-Instruct            1                 1               0
1  Llama 3.3-70B-Instruct            1                 1               1
2  Llama 3.3-70B-Instruct            1                 1               2

                                           reasoning
0  The medical student's answer demonstrates a ge...
1  The medical student's answer demonstrates a mo...
2  The medical student's answer demonstrates a co...

In [20]:
df_reason = pd.read_csv("all_questions_answers_scores_plus_reason.csv")
df_reason

,Unnamed: 0,model,category_id,iteration_number,question_index,question,model_answer,gold_answer,MedGPT1,MedGPT2,...,synonyms_lemmatized_f1_dict_bipartite,synonyms_lemmatized_precision_dict_one2many,synonyms_lemmatized_recall_dict_one2many,synonyms_lemmatized_f1_dict_one2many,synonyms_lemmatized_precision_snomed,synonyms_lemmatized_recall_snomed,synonyms_lemmatized_f1_snomed,synonyms_lemmatized_precision_wn,synonyms_lemmatized_recall_wn,synonyms_lemmatized_f1_wn
0,0,Llama 3.3-70B-Instruct,1,1,0,How is HIV diagnosed?,HIV diagnosis typically involves a combination...,HIV is diagnosed through HIV testing. There ar...,3.0,3.0,...,0.024096,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578,0.142857,0.205882,0.168675
1,1,Llama 3.3-70B-Instruct,1,1,1,What are the different stages of HIV?,The different stages of HIV are:\n\n1. **Acute...,The different stages of HIV are either defined...,4.0,3.0,...,0.042553,0.189189,0.700000,0.297872,0.162162,0.600000,0.255319,0.135135,0.500000,0.212766
2,2,Llama 3.3-70B-Instruct,1,1,2,How is HIV transmitted?,HIV (Human Immunodeficiency Virus) is primaril...,HIV is spread from the body fluids of an infec...,4.0,4.0,...,0.097561,0.233333,0.636364,0.341463,0.133333,0.363636,0.195122,0.166667,0.454545,0.243902
3,3,Llama 3.3-70B-Instruct,1,1,3,What comorbidities are common among people liv...,People living with HIV often experience variou...,The most common comorbidities amongst patients...,3.0,3.0,...,0.000000,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593
4,4,Llama 3.3-70B-Instruct,1,1,4,How can HIV be prevented?,HIV prevention methods include:\n\n1. **Using ...,HIV prevention involves several key strategies...,4.0,4.0,...,0.083333,0.468750,0.375000,0.416667,0.437500,0.350000,0.388889,0.437500,0.350000,0.388889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913,5413,Llama 3.1-8B-Instruct RAG,5,5,19,A 32-year-old man with a past medical history ...,Based on the provided clinical presentation an...,The etiology of these lesions is HPV (types 6 ...,4.0,4.0,...,0.000000,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857
4914,5414,Llama 3.1-8B-Instruct RAG,5,5,20,"A 24-year-old man, who recently migrated from ...","Based on the provided clinical scenario, the p...",Continue antitubercular therapy and antiretrov...,3.0,2.0,...,0.000000,0.037037,0.500000,0.068966,0.018519,0.250000,0.034483,0.037037,0.500000,0.068966
4915,5415,Llama 3.1-8B-Instruct RAG,5,5,21,A 37-year-old African-American man presents to...,"Based on the provided clinical scenario, I wou...",Focal segmental glomerulosclerosis (FSGS) asso...,4.0,4.0,...,0.000000,0.090909,0.571429,0.156863,0.068182,0.428571,0.117647,0.068182,0.428571,0.117647
4916,5416,Llama 3.1-8B-Instruct RAG,5,5,22,A 39-year-old man comes to the emergency depar...,Based on the provided clinical scenario and th...,A Treponemal test is most likely to confirm th...,1.0,1.0,...,0.000000,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455
4917,5417,Llama 3.1-8B-Instruct RAG,5,5,23,A 51-year-old woman with AIDS presents to her ...,The patient's presentation with decreased urin...,Tumor lysis syndrome is the most likely diagno...,4.0,3.0,...,0.000000,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897

In [24]:
df_reason["model"].value_counts()

model
Llama 3.3-70B-Instruct       410
Meditron 3-70B               410
NVLM-70B                     410
Claude 3.5 Sonnet            410
Llama 3.1-8B-Instruct        410
Llama 3.2-1B-Instruct        410
Gemini 2.5 Pro               410
Gemma 3 27B                  410
MedGemma 27B                 410
MedGemma 27B RAG             410
Llama 3.1-8B-Instruct RAG    410
Med42-70B                    408
Name: count, dtype: int64