In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("./all_questions_answers_scores.csv")
df.columns

Index(['Unnamed: 0', 'model', 'category_id', 'iteration_number',
       'question_index', 'question', 'model_answer', 'gold_answer', 'MedGPT1',
       'MedGPT2', 'MedGPT3', 'MedGPT4', 'MedGPT5', 'MedGPT_overall_score',
       'precision', 'recall', 'f1_score', 'synonyms_precision_dict',
       'synonyms_recall_dict', 'synonyms_f1_dict', 'synonyms_precision_snomed',
       'synonyms_recall_snomed', 'synonyms_f1_snomed', 'synonyms_precision_wn',
       'synonyms_recall_wn', 'synonyms_f1_wn',
       'synonyms_lemmatized_precision_dict', 'synonyms_lemmatized_recall_dict',
       'synonyms_lemmatized_f1_dict',
       'synonyms_lemmatized_precision_dict_bipartite',
       'synonyms_lemmatized_recall_dict_bipartite',
       'synonyms_lemmatized_f1_dict_bipartite',
       'synonyms_lemmatized_precision_dict_one2many',
       'synonyms_lemmatized_recall_dict_one2many',
       'synonyms_lemmatized_f1_dict_one2many',
       'synonyms_lemmatized_precision_snomed',
       'synonyms_lemmatized_recall_snomed', 'synonyms_lemmatized_f1_snomed',
       'synonyms_lemmatized_precision_wn', 'synonyms_lemmatized_recall_wn',
       'synonyms_lemmatized_f1_wn'],
      dtype='object')

In [17]:
df

,Unnamed: 0,model,category_id,iteration_number,question_index,question,model_answer,gold_answer,MedGPT1,MedGPT2,...,synonyms_lemmatized_f1_dict_bipartite,synonyms_lemmatized_precision_dict_one2many,synonyms_lemmatized_recall_dict_one2many,synonyms_lemmatized_f1_dict_one2many,synonyms_lemmatized_precision_snomed,synonyms_lemmatized_recall_snomed,synonyms_lemmatized_f1_snomed,synonyms_lemmatized_precision_wn,synonyms_lemmatized_recall_wn,synonyms_lemmatized_f1_wn
0,0,Llama 3.3-70B-Instruct,1,1,0,How is HIV diagnosed?,HIV diagnosis typically involves a combination...,HIV is diagnosed through HIV testing. There ar...,3.0,3.0,...,0.024096,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578,0.142857,0.205882,0.168675
1,1,Llama 3.3-70B-Instruct,1,1,1,What are the different stages of HIV?,The different stages of HIV are:\n\n1. **Acute...,The different stages of HIV are either defined...,4.0,3.0,...,0.042553,0.189189,0.700000,0.297872,0.162162,0.600000,0.255319,0.135135,0.500000,0.212766
2,2,Llama 3.3-70B-Instruct,1,1,2,How is HIV transmitted?,HIV (Human Immunodeficiency Virus) is primaril...,HIV is spread from the body fluids of an infec...,4.0,4.0,...,0.097561,0.233333,0.636364,0.341463,0.133333,0.363636,0.195122,0.166667,0.454545,0.243902
3,3,Llama 3.3-70B-Instruct,1,1,3,What comorbidities are common among people liv...,People living with HIV often experience variou...,The most common comorbidities amongst patients...,3.0,3.0,...,0.000000,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593
4,4,Llama 3.3-70B-Instruct,1,1,4,How can HIV be prevented?,HIV prevention methods include:\n\n1. **Using ...,HIV prevention involves several key strategies...,4.0,4.0,...,0.083333,0.468750,0.375000,0.416667,0.437500,0.350000,0.388889,0.437500,0.350000,0.388889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913,5413,Llama 3.1-8B-Instruct RAG,5,5,19,A 32-year-old man with a past medical history ...,Based on the provided clinical presentation an...,The etiology of these lesions is HPV (types 6 ...,4.0,4.0,...,0.000000,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857
4914,5414,Llama 3.1-8B-Instruct RAG,5,5,20,"A 24-year-old man, who recently migrated from ...","Based on the provided clinical scenario, the p...",Continue antitubercular therapy and antiretrov...,3.0,2.0,...,0.000000,0.037037,0.500000,0.068966,0.018519,0.250000,0.034483,0.037037,0.500000,0.068966
4915,5415,Llama 3.1-8B-Instruct RAG,5,5,21,A 37-year-old African-American man presents to...,"Based on the provided clinical scenario, I wou...",Focal segmental glomerulosclerosis (FSGS) asso...,4.0,4.0,...,0.000000,0.090909,0.571429,0.156863,0.068182,0.428571,0.117647,0.068182,0.428571,0.117647
4916,5416,Llama 3.1-8B-Instruct RAG,5,5,22,A 39-year-old man comes to the emergency depar...,Based on the provided clinical scenario and th...,A Treponemal test is most likely to confirm th...,1.0,1.0,...,0.000000,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455
4917,5417,Llama 3.1-8B-Instruct RAG,5,5,23,A 51-year-old woman with AIDS presents to her ...,The patient's presentation with decreased urin...,Tumor lysis syndrome is the most likely diagno...,4.0,3.0,...,0.000000,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897

In [11]:
df["category_id"].value_counts()

category_id
3    1438
5    1200
2     720
1     660
4     660
Name: count, dtype: int64

In [12]:
df["question_index"].value_counts()

question_index
0     290
6     290
1     290
10    290
9     290
7     290
8     290
5     290
4     290
3     290
2     290
11    170
18    110
22    110
21    110
20    110
19    110
23    110
17    110
16    110
15    110
14    110
13    110
12    108
Name: count, dtype: int64

In [13]:
df["model"].value_counts()

model
Llama 3.3-70B-Instruct       410
Meditron 3-70B               410
NVLM-70B                     410
Claude 3.5 Sonnet            410
Llama 3.1-8B-Instruct        410
Llama 3.2-1B-Instruct        410
Gemini 2.5 Pro               410
Gemma 3 27B                  410
MedGemma 27B                 410
Med42-70B                    408
MedGemma 27B RAG             290
Llama 3.1-8B-Instruct RAG    290
Name: count, dtype: int64

In [14]:
df["iteration_number"].value_counts()

iteration_number
1    936
4    936
5    936
2    935
3    935
Name: count, dtype: int64

In [8]:
import os
import re
import json
import glob
import pandas as pd

# ----------------------------
# 1) Load CSV
# ----------------------------
df = pd.read_csv("all_questions_answers_scores.csv")

# Add "reasoning" column right after MedGPT5
insert_at = df.columns.get_loc("MedGPT5") + 1
if "reasoning" not in df.columns:
    df.insert(insert_at, "reasoning", pd.NA)

GOLD_MODEL_NAME = "Rephrased Gold Answers"

GOLD_BASE_DIR = (
    "/cluster/home/gcardenal/HIV/medical_llm_evaluation/"
    "deploy_medical_llm_evaluation/gold_standard_rephrasing/"
    "results-GPT-score-rephrased"
)

# ----------------------------
# 2) Helpers to parse scoring files
# ----------------------------
FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL | re.IGNORECASE)

def extract_json_from_response(text: str) -> dict | None:
    """Extract the JSON object inside ```json ...``` from a string."""
    if not isinstance(text, str):
        return None
    m = FENCE_RE.search(text)
    if not m:
        return None
    blob = m.group(1).strip()
    try:
        return json.loads(blob)
    except json.JSONDecodeError:
        return None

def extract_reason(text: str) -> str | None:
    """
    Extract the 'reason' field from the JSON embedded in the 'response' string.
    Returns None if not found / not parseable.
    """
    obj = extract_json_from_response(text)
    if isinstance(obj, dict) and "reason" in obj and isinstance(obj["reason"], str):
        return obj["reason"].strip()
    return None

# Example filename:
# GPT-score_Claude_answers_category_1.2_HIV_EQ.json
# GPT-score_Llama-1B_answers_category_1.4_HIV_EQ.json
NAME_RE = re.compile(r"answers_category_(\d+)\.(\d+)_", re.IGNORECASE)

def parse_category_iteration_from_filename(path: str) -> tuple[int, int] | None:
    """Return (category_id, iteration_number) from filename, or None."""
    base = os.path.basename(path)
    m = NAME_RE.search(base)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))

def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())

# ----------------------------
# 3) Build a mapping: folder_name -> df.model value
#    (Auto-guess; you can override with a manual dict if needed)
# ----------------------------
models_root = "."  # your folders are in the current directory per your listing
df_models = sorted(df["model"].dropna().unique().tolist())
df_models_norm = {m: norm(m) for m in df_models}

# List folders in root that might contain GPT-score_*.json
candidate_dirs = [
    d for d in os.listdir(models_root)
    if os.path.isdir(os.path.join(models_root, d))
]

folder_to_model = {}
unmatched_folders = []

for folder in candidate_dirs:
    # Only consider folders that actually have GPT-score jsons somewhere inside
    folder_path = os.path.join(models_root, folder)
    has_json = bool(glob.glob(os.path.join(folder_path, "**", "GPT-score_*.json"), recursive=True))
    if not has_json:
        continue

    f_norm = norm(folder)

    # best match: folder name contained in model name (or vice versa)
    best = None
    for m in df_models:
        mn = df_models_norm[m]
        if f_norm and (f_norm in mn or mn in f_norm):
            best = m
            break

    if best is None:
        unmatched_folders.append(folder)
    else:
        folder_to_model[folder] = best

# OPTIONAL: If any folders didn't match automatically, set them manually here.
# Example:
folder_to_model.update({
     "Claude": "Claude 3.5 Sonnet",
     "Gemini_2.5Pro": "Gemini 2.5 Pro",
     "Llama_cluster": "Llama 3.3-70B-Instruct",
     "Llama-1B": "Llama 3.2-1B-Instruct",
     "Llama-8B": "Llama 3.1-8B-Instruct",
     "Gemma-3-27B": "Gemma 3 27B",
     "MedGemma-3-27B": "MedGemma 27B",
     "Med42": "Med42-70B",
     "Meditron_cluster": "Meditron 3-70B",
     "NVLM": "NVLM-70B",
     "MedGemma-3-27B-RAG": "MedGemma 27B RAG",
     "Llama-8B-RAG": "Llama 3.1-8B-Instruct RAG",
 })


print("Auto folder_to_model mapping:")
for k, v in folder_to_model.items():
    print(f"  {k} -> {v}")

if unmatched_folders:
    print("\nUnmatched folders (set these in folder_to_model.update(...) above if they contain scoring jsons):")
    for f in unmatched_folders:
        print(" ", f)

# ----------------------------
# 4) Read all GPT-score jsons and build lookup:
#    (model, category_id, iteration_number, question_index) -> reason
# ----------------------------
reason_lookup = {}

for folder, model_name in folder_to_model.items():
    folder_path = os.path.join(models_root, folder)
    json_paths = glob.glob(os.path.join(folder_path, "**", "GPT-score_*.json"), recursive=True)

    for jp in json_paths:
        ci = parse_category_iteration_from_filename(jp)
        if ci is None:
            continue
        category_id, iteration_number = ci

        try:
            with open(jp, "r", encoding="utf-8") as f:
                data = json.load(f)
        except Exception:
            continue

        # Your files are like: [ {"response": "...json..."}, {"response": "..."} , ...]
        if not isinstance(data, list):
            continue

        for i, item in enumerate(data, start=1):
            # i is the question_index within that category/iteration file
            if not isinstance(item, dict):
                continue
            reason = extract_reason(item.get("response"))
            if reason:
                reason_lookup[(model_name, category_id, iteration_number, i)] = reason

print(f"\nBuilt reason_lookup entries: {len(reason_lookup):,}")

# ----------------------------
# 4b) Read REPHRASED GOLD scoring jsons
# ----------------------------
import glob
import json

gold_jsons = glob.glob(
    os.path.join(GOLD_BASE_DIR, "GPT-score_rephrased_true_answers_answers_category_*.json")
)

print(f"Found {len(gold_jsons)} rephrased gold json files")

for jp in gold_jsons:
    ci = parse_category_iteration_from_filename(jp)
    if ci is None:
        continue

    category_id, iteration_number = ci

    try:
        with open(jp, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        continue

    if not isinstance(data, list):
        continue

    for i, item in enumerate(data, start=1):
        if not isinstance(item, dict):
            continue

        reason = extract_reason(item.get("response"))
        if reason:
            reason_lookup[
                (GOLD_MODEL_NAME, category_id, iteration_number, i)
            ] = reason

# ----------------------------
# 5) Fill df['reasoning'] by matching each row
# ----------------------------
keys = list(
    zip(df["model"], df["category_id"], df["iteration_number"], df["question_index"])
)
df["reasoning"] = [reason_lookup.get(k, pd.NA) for k in keys]

# ----------------------------
# 6) Save output
# ----------------------------
out_path = "all_questions_answers_scores_plus_reason.csv"
df.to_csv(out_path, index=False)
print(f"\nSaved: {out_path}")

# OPTIONAL sanity checks:
print("\nReasoning filled count:", df["reasoning"].notna().sum(), "/", len(df))
print("Examples (non-null):")
print(df.loc[df["reasoning"].notna(), ["model","category_id","iteration_number","question_index","reasoning"]].head(3))

Auto folder_to_model mapping:
  Claude -> Claude 3.5 Sonnet
  Gemini_2.5Pro -> Gemini 2.5 Pro
  Llama_cluster -> Llama 3.3-70B-Instruct
  Llama-1B -> Llama 3.2-1B-Instruct
  Llama-8B -> Llama 3.1-8B-Instruct
  Gemma-3-27B -> Gemma 3 27B
  MedGemma-3-27B -> MedGemma 27B
  Med42 -> Med42-70B
  Meditron_cluster -> Meditron 3-70B
  NVLM -> NVLM-70B
  MedGemma-3-27B-RAG -> MedGemma 27B RAG
  Llama-8B-RAG -> Llama 3.1-8B-Instruct RAG

Built reason_lookup entries: 0
Found 30 rephrased gold json files

Saved: all_questions_answers_scores_plus_reason.csv

Reasoning filled count: 0 / 4678
Examples (non-null):
Empty DataFrame
Columns: [model, category_id, iteration_number, question_index, reasoning]
Index: []

In [21]:
GOLD_MODEL_NAME = "Rephrased Gold Answers"

GOLD_BASE_DIR = (
    "/cluster/home/gcardenal/HIV/medical_llm_evaluation/"
    "deploy_medical_llm_evaluation/gold_standard_rephrasing/"
    "results-GPT-score-rephrased"
)

In [22]:
# ----------------------------
# 4b) Read REPHRASED GOLD scoring jsons
# ----------------------------
import glob
import json

gold_jsons = glob.glob(
    os.path.join(GOLD_BASE_DIR, "GPT-score_rephrased_true_answers_answers_category_*.json")
)

print(f"Found {len(gold_jsons)} rephrased gold json files")

for jp in gold_jsons:
    ci = parse_category_iteration_from_filename(jp)
    if ci is None:
        continue

    category_id, iteration_number = ci

    try:
        with open(jp, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        continue

    if not isinstance(data, list):
        continue

    for i, item in enumerate(data, start=1):
        if not isinstance(item, dict):
            continue

        reason = extract_reason(item.get("response"))
        if reason:
            reason_lookup[
                (GOLD_MODEL_NAME, category_id, iteration_number, i)
            ] = reason

Found 30 rephrased gold json files

In [27]:
import os
import re
import json
import glob
import pandas as pd

# ----------------------------
# 1) Load CSV
# ----------------------------
df = pd.read_csv("all_questions_answers_scores.csv")

# Insert "reasoning" right after MedGPT5
insert_at = df.columns.get_loc("MedGPT5") + 1
if "reasoning" not in df.columns:
    df.insert(insert_at, "reasoning", pd.NA)

# ----------------------------
# 2) Paths / constants
# ----------------------------
models_root = "/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score"  # your notebook working dir: model_answers/results-GPT-score/

GOLD_MODEL_NAME = "Rephrased Gold Answers"
GOLD_BASE_DIR = (
    "/cluster/home/gcardenal/HIV/medical_llm_evaluation/"
    "deploy_medical_llm_evaluation/gold_standard_rephrasing/"
    "results-GPT-score-rephrased"
)

# ----------------------------
# 3) Helpers
# ----------------------------
FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL | re.IGNORECASE)
NAME_RE = re.compile(r"answers_category_(\d+)\.(\d+)_", re.IGNORECASE)

def extract_json_from_response(text: str):
    if not isinstance(text, str):
        return None
    m = FENCE_RE.search(text)
    if not m:
        return None
    try:
        return json.loads(m.group(1).strip())
    except json.JSONDecodeError:
        return None

def extract_reason(text: str):
    obj = extract_json_from_response(text)
    if isinstance(obj, dict) and isinstance(obj.get("reason"), str):
        return obj["reason"].strip()
    return None

def parse_category_iteration_from_filename(path: str):
    base = os.path.basename(path)
    m = NAME_RE.search(base)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))

def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())

# ----------------------------
# 4) Map folders -> df.model names (you already have a good manual map)
# ----------------------------
folder_to_model = {
    'Llama': 'Llama 3.3-70B-Instruct',
    'Meditron': 'Meditron 3-70B',
    'Llama-8B': 'Llama 3.1-8B-Instruct',
    'Claude': 'Claude 3.5 Sonnet',
    'Med42': 'Med42-70B',
    'NVLM': 'NVLM-70B', 
    'Llama-1B': 'Llama 3.2-1B-Instruct',
    'Gemini_2.5Pro': 'Gemini 2.5 Pro',
    'Gemma-3-27B' : 'Gemma 3 27B', 
    'MedGemma-3-27B' : 'MedGemma 27B',
    "MedGemma-3-27B-RAG": "MedGemma 27B RAG",
    "Llama-8B-RAG": "Llama 3.1-8B-Instruct RAG",
    'rephrased_true_answers': 'Rephrased Gold Answers'
}

# ----------------------------
# 5) Build mapping:
#    (model, category_id, iteration_number) -> list_of_reasons_in_order
# ----------------------------
reasons_by_group = {}

def add_file_reasons(model_name: str, json_path: str):
    ci = parse_category_iteration_from_filename(json_path)
    if ci is None:
        return
    category_id, iteration_number = ci

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return

    if not isinstance(data, list):
        return

    reasons = []
    for item in data:
        if not isinstance(item, dict):
            continue
        r = extract_reason(item.get("response"))
        reasons.append(r)  # keep position even if None (preserves alignment)

    reasons_by_group[(model_name, category_id, iteration_number)] = reasons

# --- regular model folders ---
for folder, model_name in folder_to_model.items():
    folder_path = os.path.join(models_root, folder)
    json_paths = glob.glob(os.path.join(folder_path, "**", "GPT-score_*.json"), recursive=True)
    for jp in json_paths:
        add_file_reasons(model_name, jp)

# --- gold rephrased folder ---
gold_paths = glob.glob(
    os.path.join(GOLD_BASE_DIR, "GPT-score_rephrased_true_answers_answers_category_*.json")
)
for jp in gold_paths:
    add_file_reasons(GOLD_MODEL_NAME, jp)

print(f"Loaded reason lists for groups: {len(reasons_by_group):,}")

# ----------------------------
# 6) Fill df['reasoning'] by group order (sorted by question_index)
# ----------------------------
df["reasoning"] = pd.NA  # reset in case rerun

filled = 0
for (model_name, category_id, iteration_number), idxs in df.groupby(
    ["model", "category_id", "iteration_number"]
).groups.items():

    reasons = reasons_by_group.get((model_name, int(category_id), int(iteration_number)))
    if not reasons:
        continue

    # assign by CSV question order
    group_index_list = list(idxs)
    group_sorted = sorted(group_index_list, key=lambda i: df.at[i, "question_index"])

    n = min(len(group_sorted), len(reasons))
    for k in range(n):
        r = reasons[k]
        if r:  # only fill if we successfully extracted a reason
            df.at[group_sorted[k], "reasoning"] = r
            filled += 1

print("Reasoning filled cells:", filled)

# ----------------------------
# 7) Save output
# ----------------------------
out_path = "all_questions_answers_scores_plus_reason.csv"
df.to_csv(out_path, index=False)
print("Saved:", out_path)

# quick sanity:
print("Non-null reasoning:", df["reasoning"].notna().sum(), "/", len(df))
print(df.loc[df["reasoning"].notna(), ["model","category_id","iteration_number","question_index","reasoning"]].head(3))

Loaded reason lists for groups: 320
Reasoning filled cells: 4079
Saved: all_questions_answers_scores_plus_reason.csv
Non-null reasoning: 4079 / 4918
        model  category_id  iteration_number  question_index  \
820  NVLM-70B            1                 1               0
821  NVLM-70B            1                 1               1
822  NVLM-70B            1                 1               2

                                             reasoning
820  The medical student's answer demonstrates a ge...
821  The medical student's answer demonstrates a co...
822  The medical student's answer demonstrates a co...

In [30]:
import os
import re
import json
import glob
import pandas as pd

# ----------------------------
# 1) Load CSV
# ----------------------------
df = pd.read_csv("all_questions_answers_scores.csv")

# Insert "reasoning" right after MedGPT5
insert_at = df.columns.get_loc("MedGPT5") + 1
if "reasoning" not in df.columns:
    df.insert(insert_at, "reasoning", pd.NA)

# ----------------------------
# 2) Paths / constants
# ----------------------------
models_root = "/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score"  # your notebook working dir: model_answers/results-GPT-score/

GOLD_MODEL_NAME = "Rephrased Gold Answers"
GOLD_BASE_DIR = (
    "/cluster/home/gcardenal/HIV/medical_llm_evaluation/"
    "deploy_medical_llm_evaluation/gold_standard_rephrasing/"
    "results-GPT-score-rephrased"
)

# ----------------------------
# 3) Helpers
# ----------------------------
FENCE_RE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.DOTALL | re.IGNORECASE)
NAME_RE = re.compile(r"answers_category_(\d+)\.(\d+)_", re.IGNORECASE)

def extract_json_from_response(text: str):
    if not isinstance(text, str):
        return None
    m = FENCE_RE.search(text)
    if not m:
        return None
    try:
        return json.loads(m.group(1).strip())
    except json.JSONDecodeError:
        return None

def extract_reason(text: str):
    obj = extract_json_from_response(text)
    if isinstance(obj, dict) and isinstance(obj.get("reason"), str):
        return obj["reason"].strip()
    return None

def parse_category_iteration_from_filename(path: str):
    base = os.path.basename(path)
    m = NAME_RE.search(base)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))

def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())

# ----------------------------
# 4) Map folders -> df.model names
# ----------------------------
folder_to_model = {
    "Claude": "Claude 3.5 Sonnet",
    "Gemini_2.5Pro": "Gemini 2.5 Pro",
    "Llama_cluster": "Llama 3.3-70B-Instruct",
    "Llama-1B": "Llama 3.2-1B-Instruct",
    "Llama-8B": "Llama 3.1-8B-Instruct",
    "Gemma-3-27B": "Gemma 3 27B",
    "MedGemma-3-27B": "MedGemma 27B",
    "Med42": "Med42-70B",
    "Meditron_cluster": "Meditron 3-70B",
    "NVLM": "NVLM-70B",
    "MedGemma-3-27B-RAG": "MedGemma 27B RAG",
    "Llama-8B-RAG": "Llama 3.1-8B-Instruct RAG",
}

# ----------------------------
# 5) Build mapping:
#    (model, category_id, iteration_number) -> list_of_reasons_in_order
#    + diagnostics: (model, cat, iter, json_path) -> list of entry indices where reason is None
# ----------------------------
reasons_by_group = {}
none_reason_entries = {}  # key: (model, category, iter, path) -> [entry_idx, ...]

def add_file_reasons(model_name: str, json_path: str):
    ci = parse_category_iteration_from_filename(json_path)
    if ci is None:
        return
    category_id, iteration_number = ci

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return

    if not isinstance(data, list):
        return

    reasons = []
    none_idxs = []

    for idx, item in enumerate(data):
        if not isinstance(item, dict):
            reasons.append(None)
            none_idxs.append(idx)
            continue

        r = extract_reason(item.get("response"))
        reasons.append(r)  # keep position even if None (preserves alignment)

        if r is None:
            none_idxs.append(idx)

    reasons_by_group[(model_name, category_id, iteration_number)] = reasons

    if none_idxs:
        none_reason_entries[(model_name, category_id, iteration_number, json_path)] = none_idxs

# --- regular model folders ---
for folder, model_name in folder_to_model.items():
    folder_path = os.path.join(models_root, folder)
    json_paths = glob.glob(os.path.join(folder_path, "**", "GPT-score_*.json"), recursive=True)
    for jp in json_paths:
        add_file_reasons(model_name, jp)

# --- gold rephrased folder ---
gold_paths = glob.glob(
    os.path.join(GOLD_BASE_DIR, "GPT-score_rephrased_true_answers_answers_category_*.json")
)
for jp in gold_paths:
    add_file_reasons(GOLD_MODEL_NAME, jp)

print(f"Loaded reason lists for groups: {len(reasons_by_group):,}")

# ----------------------------
# 6) Fill df['reasoning'] by group order (sorted by question_index)
#    + track which df rows were expected to have reasoning (group exists)
# ----------------------------
df["reasoning"] = pd.NA  # reset in case rerun

expected_reasoning_rows = set()
filled = 0

for (model_name, category_id, iteration_number), idxs in df.groupby(
    ["model", "category_id", "iteration_number"]
).groups.items():

    reasons = reasons_by_group.get((model_name, int(category_id), int(iteration_number)))
    if not reasons:
        continue

    # these rows correspond to a group that exists in JSON => "expected"
    expected_reasoning_rows.update(idxs)

    # assign by CSV question order
    group_index_list = list(idxs)
    group_sorted = sorted(group_index_list, key=lambda i: df.at[i, "question_index"])

    n = min(len(group_sorted), len(reasons))
    for k in range(n):
        r = reasons[k]
        if r:  # only fill if we successfully extracted a reason
            df.at[group_sorted[k], "reasoning"] = r
            filled += 1

print("Reasoning filled cells:", filled)

# ----------------------------
# 6b) Diagnostics
# ----------------------------

# A) Rows that belong to a group with JSONs but still have null reasoning
null_expected_mask = df.index.isin(expected_reasoning_rows) & df["reasoning"].isna()
null_expected_df = df.loc[
    null_expected_mask,
    ["model", "category_id", "iteration_number", "question_index"]
].sort_values(["model", "category_id", "iteration_number", "question_index"])

print("\nNull reasoning rows (group matched but no reason extracted):")
print(f"{len(null_expected_df)} rows")
print(null_expected_df.head(50))

# B) Rows with NO matching JSON group at all
all_group_keys = set(reasons_by_group.keys())
df_group_keys = set(
    (row.model, int(row.category_id), int(row.iteration_number))
    for row in df.itertuples()
)
unmatched_groups = df_group_keys - all_group_keys

unmatched_mask = df.apply(
    lambda r: (r.model, int(r.category_id), int(r.iteration_number)) in unmatched_groups,
    axis=1,
)
unmatched_df = df.loc[
    unmatched_mask,
    ["model", "category_id", "iteration_number", "question_index"]
].sort_values(["model", "category_id", "iteration_number", "question_index"])

print("\nRows with NO matching JSON group at all:")
print(f"{len(unmatched_df)} rows")
print(unmatched_df.head(50))

# C) Which JSON entries had None reasons (per file)
print("\nJSON entries with None reason (by file):")
if not none_reason_entries:
    print("None")
else:
    # show a compact summary
    total_none = sum(len(v) for v in none_reason_entries.values())
    print(f"Files with >=1 None reason: {len(none_reason_entries)}")
    print(f"Total None entries across those files: {total_none}")

    # print first N files (adjust as needed)
    N = 20
    shown = 0
    for (model_name, cat, it, path), idx_list in sorted(
        none_reason_entries.items(),
        key=lambda kv: (kv[0][0], kv[0][1], kv[0][2], kv[0][3]),
    ):
        print(f"- {model_name} | cat={cat} iter={it} | none_count={len(idx_list)} | file={path}")
        print(f"  entry_indices (0-based): {idx_list[:50]}" + (" ..." if len(idx_list) > 50 else ""))
        shown += 1
        if shown >= N:
            remaining = len(none_reason_entries) - N
            if remaining > 0:
                print(f"... ({remaining} more files not shown)")
            break

# ----------------------------
# 7) Save output
# ----------------------------
out_path = "all_questions_answers_scores_plus_reason.csv"
df.to_csv(out_path, index=False)
print("\nSaved:", out_path)

# quick sanity:
print("Non-null reasoning:", df["reasoning"].notna().sum(), "/", len(df))
print(
    df.loc[
        df["reasoning"].notna(),
        ["model", "category_id", "iteration_number", "question_index", "reasoning"],
    ].head(3)
)

Loaded reason lists for groups: 380
Reasoning filled cells: 4899

Null reasoning rows (group matched but no reason extracted):
19 rows
          model  category_id  iteration_number  question_index
1287  Med42-70B            2                 1               2
1290  Med42-70B            2                 1               5
1299  Med42-70B            2                 2               2
1302  Med42-70B            2                 2               5
1311  Med42-70B            2                 3               2
1323  Med42-70B            2                 4               2
1326  Med42-70B            2                 4               5
1335  Med42-70B            2                 5               2
1338  Med42-70B            2                 5               5
1357  Med42-70B            3                 1              12
1363  Med42-70B            3                 1              18
1367  Med42-70B            3                 1              22
1387  Med42-70B            3                 2              19
1410  Med42-70B            3                 3              19
1427  Med42-70B            3                 4              12
1433  Med42-70B            3                 4              18
1451  Med42-70B            3                 5              12
1457  Med42-70B            3                 5              18
1479  Med42-70B            4                 2               5

Rows with NO matching JSON group at all:
0 rows
Empty DataFrame
Columns: [model, category_id, iteration_number, question_index]
Index: []

JSON entries with None reason (by file):
Files with >=1 None reason: 11
Total None entries across those files: 19
- Med42-70B | cat=2 iter=1 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.1_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=2 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.2_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=3 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.3_HIV_EQ.json
  entry_indices (0-based): [2]
- Med42-70B | cat=2 iter=4 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.4_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=2 iter=5 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_2.5_HIV_EQ.json
  entry_indices (0-based): [2, 5]
- Med42-70B | cat=3 iter=1 | none_count=3 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.1_HIV_EQ.json
  entry_indices (0-based): [12, 18, 22]
- Med42-70B | cat=3 iter=2 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.2_HIV_EQ.json
  entry_indices (0-based): [18]
- Med42-70B | cat=3 iter=3 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.3_HIV_EQ.json
  entry_indices (0-based): [18]
- Med42-70B | cat=3 iter=4 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.4_HIV_EQ.json
  entry_indices (0-based): [12, 18]
- Med42-70B | cat=3 iter=5 | none_count=2 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_3.5_HIV_EQ.json
  entry_indices (0-based): [12, 18]
- Med42-70B | cat=4 iter=2 | none_count=1 | file=/cluster/home/gcardenal/HIV/medical_llm_evaluation/deploy_medical_llm_evaluation/model_answers/results-GPT-score/Med42/GPT-score_Med42_answers_category_4.2_HIV_EQ.json
  entry_indices (0-based): [5]

Saved: all_questions_answers_scores_plus_reason.csv
Non-null reasoning: 4899 / 4918
                    model  category_id  iteration_number  question_index  \
0  Llama 3.3-70B-Instruct            1                 1               0
1  Llama 3.3-70B-Instruct            1                 1               1
2  Llama 3.3-70B-Instruct            1                 1               2

                                           reasoning
0  The medical student's answer demonstrates a ge...
1  The medical student's answer demonstrates a mo...
2  The medical student's answer demonstrates a co...

In [20]:
df_reason = pd.read_csv("all_questions_answers_scores_plus_reason.csv")
df_reason

,Unnamed: 0,model,category_id,iteration_number,question_index,question,model_answer,gold_answer,MedGPT1,MedGPT2,...,synonyms_lemmatized_f1_dict_bipartite,synonyms_lemmatized_precision_dict_one2many,synonyms_lemmatized_recall_dict_one2many,synonyms_lemmatized_f1_dict_one2many,synonyms_lemmatized_precision_snomed,synonyms_lemmatized_recall_snomed,synonyms_lemmatized_f1_snomed,synonyms_lemmatized_precision_wn,synonyms_lemmatized_recall_wn,synonyms_lemmatized_f1_wn
0,0,Llama 3.3-70B-Instruct,1,1,0,How is HIV diagnosed?,HIV diagnosis typically involves a combination...,HIV is diagnosed through HIV testing. There ar...,3.0,3.0,...,0.024096,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578,0.142857,0.205882,0.168675
1,1,Llama 3.3-70B-Instruct,1,1,1,What are the different stages of HIV?,The different stages of HIV are:\n\n1. **Acute...,The different stages of HIV are either defined...,4.0,3.0,...,0.042553,0.189189,0.700000,0.297872,0.162162,0.600000,0.255319,0.135135,0.500000,0.212766
2,2,Llama 3.3-70B-Instruct,1,1,2,How is HIV transmitted?,HIV (Human Immunodeficiency Virus) is primaril...,HIV is spread from the body fluids of an infec...,4.0,4.0,...,0.097561,0.233333,0.636364,0.341463,0.133333,0.363636,0.195122,0.166667,0.454545,0.243902
3,3,Llama 3.3-70B-Instruct,1,1,3,What comorbidities are common among people liv...,People living with HIV often experience variou...,The most common comorbidities amongst patients...,3.0,3.0,...,0.000000,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593
4,4,Llama 3.3-70B-Instruct,1,1,4,How can HIV be prevented?,HIV prevention methods include:\n\n1. **Using ...,HIV prevention involves several key strategies...,4.0,4.0,...,0.083333,0.468750,0.375000,0.416667,0.437500,0.350000,0.388889,0.437500,0.350000,0.388889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913,5413,Llama 3.1-8B-Instruct RAG,5,5,19,A 32-year-old man with a past medical history ...,Based on the provided clinical presentation an...,The etiology of these lesions is HPV (types 6 ...,4.0,4.0,...,0.000000,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857,0.078947,0.750000,0.142857
4914,5414,Llama 3.1-8B-Instruct RAG,5,5,20,"A 24-year-old man, who recently migrated from ...","Based on the provided clinical scenario, the p...",Continue antitubercular therapy and antiretrov...,3.0,2.0,...,0.000000,0.037037,0.500000,0.068966,0.018519,0.250000,0.034483,0.037037,0.500000,0.068966
4915,5415,Llama 3.1-8B-Instruct RAG,5,5,21,A 37-year-old African-American man presents to...,"Based on the provided clinical scenario, I wou...",Focal segmental glomerulosclerosis (FSGS) asso...,4.0,4.0,...,0.000000,0.090909,0.571429,0.156863,0.068182,0.428571,0.117647,0.068182,0.428571,0.117647
4916,5416,Llama 3.1-8B-Instruct RAG,5,5,22,A 39-year-old man comes to the emergency depar...,Based on the provided clinical scenario and th...,A Treponemal test is most likely to confirm th...,1.0,1.0,...,0.000000,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455,0.023810,0.500000,0.045455
4917,5417,Llama 3.1-8B-Instruct RAG,5,5,23,A 51-year-old woman with AIDS presents to her ...,The patient's presentation with decreased urin...,Tumor lysis syndrome is the most likely diagno...,4.0,3.0,...,0.000000,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897,0.120000,0.750000,0.206897

In [24]:
df_reason["model"].value_counts()

model
Llama 3.3-70B-Instruct       410
Meditron 3-70B               410
NVLM-70B                     410
Claude 3.5 Sonnet            410
Llama 3.1-8B-Instruct        410
Llama 3.2-1B-Instruct        410
Gemini 2.5 Pro               410
Gemma 3 27B                  410
MedGemma 27B                 410
MedGemma 27B RAG             410
Llama 3.1-8B-Instruct RAG    410
Med42-70B                    408
Name: count, dtype: int64

In [23]:
def toks(s):
    return set(re.findall(r"[a-zA-Z0-9]+", str(s).lower()))

def overlap(a, b):
    A, B = toks(a), toks(b)
    return 0 if not A or not B else len(A & B) / len(A | B)

for (m, c, it), idxs in df.groupby(["model","category_id","iteration_number"]).groups.items():
    idxs = sorted(list(idxs), key=lambda i: df.at[i, "question_index"])
    if len(idxs) < 10:
        continue

    # pick the column that has the model answer you want to compare against
    ans_col = "model_answer"  # change to your real column name

    scores0, scoresP1, scoresM1 = [], [], []
    for j, i in enumerate(idxs):
        r = df.at[i, "reasoning"]
        if pd.isna(r):
            continue

        a0 = df.at[i, ans_col]
        s0 = overlap(r, a0)
        scores0.append(s0)

        if j + 1 < len(idxs):
            scoresP1.append(overlap(r, df.at[idxs[j+1], ans_col]))
        if j - 1 >= 0:
            scoresM1.append(overlap(r, df.at[idxs[j-1], ans_col]))

    if scores0:
        m0 = sum(scores0)/len(scores0)
        mp = sum(scoresP1)/len(scoresP1) if scoresP1 else 0
        mm = sum(scoresM1)/len(scoresM1) if scoresM1 else 0

        if mp > m0 + 0.02 or mm > m0 + 0.02:
            print("POSSIBLE SHIFT:", (m,c,it), "m0=", round(m0,3), "m+1=", round(mp,3), "m-1=", round(mm,3))

In [31]:
df_questions = pd.read_csv("./questions.csv")
df_questions.columns

Index(['category_id', 'question_index', 'question', 'gold_answer', 'source'], dtype='object')

In [27]:
import pandas as pd

df_new = pd.read_csv("all_questions_answers_scores_plus_reason.csv")
df_old = pd.read_csv("./all_questions_answers_scores_plus_reason_old.csv")

KEY_COLS = [
    "model",
    "category_id",
    "iteration_number",
    "question_index",
]

df_filtered = df_new.merge(
    df_old[KEY_COLS].drop_duplicates(),
    on=KEY_COLS,
    how="inner",
)

Saved: all_questions_answers_scores_plus_reason_filtered.csv
Rows kept: 2803 / 4508

In [29]:
import pandas as pd

df_new = pd.read_csv("all_questions_answers_scores_plus_reason.csv")
df_old = pd.read_csv("./all_questions_answers_scores_plus_reason_old.csv")

KEY_COLS = ["model", "category_id", "iteration_number", "question_index"]

def normalize(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df["model"] = df["model"].astype(str).str.strip()
    for c in ["category_id", "iteration_number", "question_index"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    return df

df_new_n = normalize(df_new)
df_old_n = normalize(df_old)

# ---- FIX: old question_index is 1-based, new is 0-based ----
df_old_n["question_index"] = df_old_n["question_index"] - 1

# (Optional) If you want to be strict, drop any rows that became invalid
df_old_n = df_old_n.dropna(subset=KEY_COLS)

# Filter NEW by keys present in OLD
old_keys = df_old_n[KEY_COLS].drop_duplicates()

df_filtered = df_new_n.merge(
    old_keys,
    on=KEY_COLS,
    how="inner",
)

out_path = "all_questions_answers_scores_plus_reason_filtered.csv"
df_filtered.to_csv(out_path, index=False)

print("Old rows:", len(df_old), " | unique keys:", len(old_keys))
print("New rows:", len(df_new))
print("Rows kept:", len(df_filtered), "/", len(df_new))
print("Saved:", out_path)

# Extra sanity: check if any OLD keys still missing in NEW after fix
missing = old_keys.merge(
    df_new_n[KEY_COLS].drop_duplicates(),
    on=KEY_COLS,
    how="left",
    indicator=True,
)
missing = missing[missing["_merge"] == "left_only"].drop(columns=["_merge"])
print("Unique OLD keys still missing in NEW after index shift:", len(missing))
if len(missing) > 0:
    print(missing.head(20))

Old rows: 3465  | unique keys: 3465
New rows: 4508
Rows kept: 2913 / 4508
Saved: all_questions_answers_scores_plus_reason_filtered.csv
Unique OLD keys still missing in NEW after index shift: 552
                       model  category_id  iteration_number  question_index
1403               Med42-70B            3                 3              12
1420               Med42-70B            3                 2              12
2475             Gemma 3 27B            4                 1              11
2476       Claude 3.5 Sonnet            4                 3              11
2477   Llama 3.2-1B-Instruct            4                 1              11
2478       Claude 3.5 Sonnet            4                 2              11
2479            MedGemma 27B            4                 5              11
2480                NVLM-70B            4                 2              11
2481   Llama 3.2-1B-Instruct            4                 2              11
2482            MedGemma 27B            4                 1              11
2483          Meditron 3-70B            4                 2              11
2484  Llama 3.3-70B-Instruct            4                 2              11
2485                NVLM-70B            4                 3              11
2486       Claude 3.5 Sonnet            4                 1              11
2487            MedGemma 27B            4                 3              11
2488          Gemini 2.5 Pro            4                 4              11
2489  Rephrased Gold Answers            4                 3              11
2490                NVLM-70B            4                 1              11
2491                NVLM-70B            4                 5              11
2492   Llama 3.1-8B-Instruct            4                 3              11

In [25]:
import pandas as pd
import re
import unicodedata

df_reason = pd.read_csv("all_questions_answers_scores_plus_reason.csv")
df_questions = pd.read_csv("./questions.csv")

assert "question" in df_reason.columns, "df_reason missing column: question"
assert "question" in df_questions.columns, "df_questions missing column: question"

def norm_str(s: str) -> str:
    if not isinstance(s, str):
        return ""
    # normalize unicode (quotes, accents, etc.)
    s = unicodedata.normalize("NFKC", s)

    s = s.lower().strip()
    s = re.sub(r"\s+", " ", s)  # collapse whitespace

    # remove common leading labels like "q12:", "question 12:", "12)"
    s = re.sub(r"^(question|q)\s*\d+\s*[:\)\.\-]\s*", "", s)
    s = re.sub(r"^\d+\s*[:\)\.\-]\s*", "", s)

    # remove punctuation-ish (keep alnum and spaces)
    s = re.sub(r"[^a-z0-9\s]+", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

df_reason["_q_norm"] = df_reason["question"].apply(norm_str)
df_questions["_q_norm"] = df_questions["question"].apply(norm_str)

valid = set(df_questions["_q_norm"].dropna())
print("questions.csv rows:", len(df_questions))
print("questions.csv unique normalized:", len(valid))

# overlap diagnostics
reason_unique = set(df_reason["_q_norm"].dropna())
print("df_reason rows:", len(df_reason))
print("df_reason unique normalized:", len(reason_unique))
print("normalized intersection:", len(valid & reason_unique))

# filter (keep ONLY those whose normalized question exists in questions.csv)
df_filtered = df_reason[df_reason["_q_norm"].isin(valid)].copy()
df_filtered.drop(columns=["_q_norm"], inplace=True)

out_path = "all_questions_answers_scores_plus_reason_filtered.csv"
df_filtered.to_csv(out_path, index=False)

print("Filtered rows:", len(df_filtered))
print("Saved:", out_path)

questions.csv rows: 63
questions.csv unique normalized: 63
df_reason rows: 4918
df_reason unique normalized: 83
normalized intersection: 61
Filtered rows: 3355
Saved: all_questions_answers_scores_plus_reason_filtered.csv

In [33]:
df_reason = pd.read_csv("all_questions_answers_scores_plus_reason_filtered.csv")
df_reason

,Unnamed: 0,model,category_id,iteration_number,question_index,question,model_answer,gold_answer,MedGPT1,MedGPT2,...,synonyms_lemmatized_f1_dict_bipartite,synonyms_lemmatized_precision_dict_one2many,synonyms_lemmatized_recall_dict_one2many,synonyms_lemmatized_f1_dict_one2many,synonyms_lemmatized_precision_snomed,synonyms_lemmatized_recall_snomed,synonyms_lemmatized_f1_snomed,synonyms_lemmatized_precision_wn,synonyms_lemmatized_recall_wn,synonyms_lemmatized_f1_wn
0,0,Llama 3.3-70B-Instruct,1,1,0,How is HIV diagnosed?,HIV diagnosis typically involves a combination...,HIV is diagnosed through HIV testing. There ar...,3.0,3.0,...,0.024096,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578,0.122449,0.176471,0.144578
1,1,Llama 3.3-70B-Instruct,1,1,1,What are the different stages of HIV?,The different stages of HIV are:\n\n1. **Acute...,The different stages of HIV are either defined...,4.0,3.0,...,0.042553,0.189189,0.700000,0.297872,0.162162,0.600000,0.255319,0.135135,0.500000,0.212766
2,2,Llama 3.3-70B-Instruct,1,1,2,How is HIV transmitted?,HIV (Human Immunodeficiency Virus) is primaril...,HIV is spread from the body fluids of an infec...,4.0,4.0,...,0.097561,0.233333,0.636364,0.341463,0.133333,0.363636,0.195122,0.166667,0.454545,0.243902
3,3,Llama 3.3-70B-Instruct,1,1,3,What comorbidities are common among people liv...,People living with HIV often experience variou...,The most common comorbidities amongst patients...,3.0,3.0,...,0.000000,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593,0.129032,0.142857,0.135593
4,4,Llama 3.3-70B-Instruct,1,1,4,How can HIV be prevented?,HIV prevention methods include:\n\n1. **Using ...,HIV prevention involves several key strategies...,4.0,4.0,...,0.083333,0.468750,0.375000,0.416667,0.437500,0.350000,0.388889,0.437500,0.350000,0.388889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1245,4477,Rephrased Gold Answers,5,4,17,A 25-year-old nulliparous woman at 8 weeks' ge...,The recommended diagnostic evaluations for thi...,Tests to conduct at this visit include ELISA f...,4.0,5.0,...,NaN,NaN,NaN,NaN,0.250000,0.333333,0.285714,0.250000,0.333333,0.285714
1246,4492,Rephrased Gold Answers,5,5,8,You are reviewing raw data from a research stu...,The negative predictive value (NPV) of this sc...,The NPV of this test is calculated as the prop...,5.0,5.0,...,NaN,NaN,NaN,NaN,0.285714,0.400000,0.333333,0.428571,0.600000,0.500000
1247,4494,Rephrased Gold Answers,5,5,10,A 33-year-old HIV-positive male is seen in cli...,"Alongside his antiretroviral regimen, the pati...","In addition to his antiretroviral therapy, the...",5.0,5.0,...,NaN,NaN,NaN,NaN,0.571429,0.800000,0.666667,0.571429,0.800000,0.666667
1248,4495,Rephrased Gold Answers,5,5,11,A 2300-g (5-lb 1-oz) male newborn is delivered...,The subsequent optimal intervention for this n...,The next best step in management for this infa...,5.0,5.0,...,NaN,NaN,NaN,NaN,0.200000,0.250000,0.222222,0.200000,0.250000,0.222222
1249,4501,Rephrased Gold Answers,5,5,17,A 25-year-old nulliparous woman at 8 weeks' ge...,The recommended diagnostic evaluations for thi...,Tests to conduct at this visit include ELISA f...,4.0,5.0,...,NaN,NaN,NaN,NaN,0.250000,0.333333,0.285714,0.250000,0.333333,0.285714

In [35]:
# Sets of normalized questions
reason_qs = set(df_reason["_q_norm"].dropna())
questions_qs = set(df_questions["_q_norm"].dropna())

# Questions present in questions.csv but NOT in df_reason
missing_in_reason = questions_qs - reason_qs

# Questions present in df_reason but NOT in questions.csv
extra_in_reason = reason_qs - questions_qs

print("Questions in questions.csv NOT found in df_reason:", len(missing_in_reason))
print("Questions in df_reason NOT found in questions.csv:", len(extra_in_reason))

Questions in questions.csv NOT found in df_reason: 2
Questions in df_reason NOT found in questions.csv: 22

In [36]:
if missing_in_reason:
    print("\n--- Questions in questions.csv NOT found in df_reason ---")
    for qn in missing_in_reason:
        rows = df_questions[df_questions["_q_norm"] == qn]
        for _, r in rows.iterrows():
            print("\nRAW QUESTION (questions.csv):")
            print(r["question"])
            print("NORMALIZED:")
            print(qn)

--- Questions in questions.csv NOT found in df_reason ---

RAW QUESTION (questions.csv):
A 35-year-old man comes to the emergency department with fever, chills, dyspnea, and a productive cough. His symptoms began suddenly 2 days ago. He was diagnosed with HIV 4 years ago and has been on triple antiretroviral therapy since then. He smokes one pack of cigarettes daily. He is 181 cm (5 ft 11 in) tall and weighs 70 kg (154 lb); BMI is 21.4 kg/m_. He lives in Illinois and works as a carpenter. His temperature is 38.8�C (101.8�F), pulse is 110/min, respirations are 24/min, and blood pressure is 105/74 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 92%. Examination reveals crackles over the right lower lung base. The remainder of the examination shows no abnormalities.

Laboratory studies show:
Hemoglobin: 11.5 g/dL
Leukocyte count: 12,800/mm_
Segmented neutrophils: 80%
Eosinophils: 1%
Lymphocytes: 17%
Monocytes: 2%
CD4+ T-lymphocytes: 520/mm_ (N � 500)
Platelet count: 258,000/mm_

Serum:
Na_: 137 mEq/L
Cl_: 102 mEq/L
K_: 5.0 mEq/L
HCO__: 22 mEq/L
Glucose: 92 mg/dL

A chest x-ray shows a right lower-lobe infiltrate of the lung.

 What is the most likely causal organism?
NORMALIZED:
a 35yearold man comes to the emergency department with fever chills dyspnea and a productive cough his symptoms began suddenly 2 days ago he was diagnosed with hiv 4 years ago and has been on triple antiretroviral therapy since then he smokes one pack of cigarettes daily he is 181 cm 5 ft 11 in tall and weighs 70 kg 154 lb bmi is 214 kgm he lives in illinois and works as a carpenter his temperature is 388c 1018f pulse is 110min respirations are 24min and blood pressure is 10574 mm hg pulse oximetry on room air shows an oxygen saturation of 92 examination reveals crackles over the right lower lung base the remainder of the examination shows no abnormalities laboratory studies show hemoglobin 115 gdl leukocyte count 12800mm segmented neutrophils 80 eosinophils 1 lymphocytes 17 monocytes 2 cd4 tlymphocytes 520mm n 500 platelet count 258000mm serum na 137 meql cl 102 meql k 50 meql hco 22 meql glucose 92 mgdl a chest xray shows a right lowerlobe infiltrate of the lung what is the most likely causal organism

RAW QUESTION (questions.csv):
A 35-year-old man comes to the emergency department with fever, chills, dyspnea, and a productive cough. His symptoms began suddenly 2 days ago. He was diagnosed with HIV 4 years ago and has been on triple antiretroviral therapy since then. He smokes one pack of cigarettes daily. He is 181 cm (5 ft 11 in) tall and weighs 70 kg (154 lb); BMI is 21.4 kg/m_. He lives in Illinois and works as a carpenter. His temperature is 38.8�C (101.8�F), pulse is 110/min, respirations are 24/min, and blood pressure is 105/74 mm Hg. Pulse oximetry on room air shows an oxygen saturation of 92%. Examination reveals crackles over the right lower lung base. The remainder of the examination shows no abnormalities.

Laboratory studies show:
Hemoglobin: 11.5 g/dL
Leukocyte count: 12,800/mm_
Segmented neutrophils: 80%
Eosinophils: 1%
Lymphocytes: 17%
Monocytes: 2%
CD4+ T-lymphocytes: 520/mm_ (N � 500)
Platelet count: 258,000/mm_

Serum:
Na_: 137 mEq/L
Cl_: 102 mEq/L
K_: 5.0 mEq/L
HCO__: 22 mEq/L
Glucose: 92 mg/dL

A chest x-ray shows a right lower-lobe infiltrate of the lung.

Recently, there was a patient with similar symptoms originated by Staphylococcus aureus. What is the most likely causal organism?
NORMALIZED:
a 35yearold man comes to the emergency department with fever chills dyspnea and a productive cough his symptoms began suddenly 2 days ago he was diagnosed with hiv 4 years ago and has been on triple antiretroviral therapy since then he smokes one pack of cigarettes daily he is 181 cm 5 ft 11 in tall and weighs 70 kg 154 lb bmi is 214 kgm he lives in illinois and works as a carpenter his temperature is 388c 1018f pulse is 110min respirations are 24min and blood pressure is 10574 mm hg pulse oximetry on room air shows an oxygen saturation of 92 examination reveals crackles over the right lower lung base the remainder of the examination shows no abnormalities laboratory studies show hemoglobin 115 gdl leukocyte count 12800mm segmented neutrophils 80 eosinophils 1 lymphocytes 17 monocytes 2 cd4 tlymphocytes 520mm n 500 platelet count 258000mm serum na 137 meql cl 102 meql k 50 meql hco 22 meql glucose 92 mgdl a chest xray shows a right lowerlobe infiltrate of the lung recently there was a patient with similar symptoms originated by staphylococcus aureus what is the most likely causal organism